# Banner
author: 'Megan Sumner'
tagline: 'Copywriter, Editor, Stick-Figurer(er).'
email: "megan(who is 'at' this)megansumner.com"

# Metadata
title: Megan Sumner
description: 'Megan Sumner: Copywriter, Editor, Stick-Figurer(er).'
url: 'megansumner.com'
keywords: 'copy, copywriter, edit, funny, comedy'

# Footer
copyright:
    year: 2012
    note: all rights reserved

# Technical
extends: base.j2
default_block: main
