# Banner
author: 'Megan Sumner'
tagline: 'Copywriter, Editor, Stick-Figurer(er).'
email: "megan(who is 'at' this)megansumner.com"

# Metadata
url: 'megansumner.com'
keywords: 'copy, copywriter, edit, funny, comedy'
description: 'Megan Sumner: Copywriter, Editor, Stick-Figurer(er).'
